from .base import *

DEBUG = False

PYTHONANYWHERE_HOST = config("PYTHONANYWHERE_HOST")

ALLOWED_HOSTS = [PYTHONANYWHERE_HOST]
CSRF_TRUSTED_ORIGINS = [f"https://{PYTHONANYWHERE_HOST}"]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True