# Generated by Django 5.2.4 on 2026-07-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_websitecontactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product'),
        ),
    ]
