# Generated by Django 5.2.4 on 2026-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactenquiry_customerreview_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='banners/')),
                ('image_alt', models.CharField(max_length=255)),
                ('link_url', models.CharField(default='/catalog/', max_length=500)),
                ('link_label', models.CharField(default='Explore', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='display_size',
            field=models.CharField(choices=[('standard', 'Standard'), ('wide', 'Wide'), ('tall', 'Tall')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
