# Generated by Django 5.2.4 on 2026-08-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner_alter_galleryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
