# Generated by Django 5.2.4 on 2026-08-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_submissionfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_display', models.CharField(default='089 948 0832', max_length=50)),
                ('phone_link', models.CharField(default='+353899480832', help_text='International format used by click-to-call links.', max_length=50)),
                ('email', models.EmailField(default='larkfencing@yahoo.com', max_length=254)),
                ('business_hours', models.CharField(default='Mon–Fri 8:30am–5pm · Sat 9am–5pm', max_length=200)),
                ('primary_location_name', models.CharField(default='Walkinstown', max_length=100)),
                ('primary_address', models.TextField(default='9 Lower Ballymount Road\nWalkinstown, Dublin 12, D12 E398')),
                ('secondary_location_name', models.CharField(blank=True, default='Johnstown yard', max_length=100)),
                ('secondary_address', models.TextField(blank=True, default='Unit 10, Westown Wood\nJohnstown, Naas, Co. Kildare, W91 TK29')),
                ('map_url', models.URLField(default='https://www.google.com/maps/search/?api=1&query=Lark+Fencing', max_length=2000)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL used by the contact-page iframe.', max_length=2000)),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('pinterest_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('tiktok_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Website settings',
            },
        ),
    ]
