# Generated by Django 5.2.4 on 2026-08-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_website_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=50)),
                ('key', models.SlugField(help_text='Template identifier; do not change after creation.', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable dashboard label.', max_length=150)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Website content',
                'ordering': ('page', 'label'),
            },
        ),
    ]
