# Generated by Django 5.2.4 on 2026-08-18 12:58

import datetime

from django.db import migrations, models


POLICIES = (
    {
        "title": "Terms and conditions",
        "slug": "terms-and-conditions",
        "summary": "The terms that apply when you browse this website, request a quote, or place an order with LARK Fencing.",
        "body": """
<section><h2>About these terms</h2><p>These terms apply to use of this website and orders placed with LARK Fencing. Our contact details are shown on this website and may be used for questions before ordering.</p></section>
<section><h2>Products, prices and quotes</h2><p>We try to keep descriptions, availability and prices accurate. Product images may differ slightly because timber and other materials naturally vary. A quote may be required where a price, delivery charge, fitting work or site condition needs confirmation.</p><p>Prices are displayed in euro and include taxes where stated. We will tell you the total price and any delivery or fitting charge before the order is binding.</p></section>
<section><h2>Orders and payment</h2><p>Submitting an order is an offer to buy. We may contact you to verify stock, delivery access, measurements or other details before confirming it. The website currently accepts cash on delivery only; no card details are requested or stored.</p></section>
<section><h2>Delivery, fitting and access</h2><p>You must provide accurate delivery details and tell us about access restrictions. Dates are estimates unless we expressly agree a fixed date. Installation work may require a separate written quote and site review.</p></section>
<section><h2>Cancellations and problems</h2><p>Cancellation and return rights are explained in our Cancellation and returns policy. Nothing in these terms limits rights that cannot legally be excluded, including rights relating to faulty or misdescribed goods.</p></section>
<section><h2>Website use and liability</h2><p>You may use this website for lawful personal or business enquiries. We are not responsible for losses caused by information you supplied incorrectly, events outside our reasonable control, or uses of a product contrary to supplied instructions, subject always to mandatory consumer law.</p></section>
<section><h2>Governing law and contact</h2><p>These terms are governed by Irish law. If you have a complaint, contact us first so we can try to resolve it. Consumers may also have access to statutory complaint and court processes.</p></section>""",
        "display_order": 10,
    },
    {
        "title": "Privacy policy",
        "slug": "privacy-policy",
        "summary": "How LARK Fencing collects, uses, retains and protects personal information.",
        "body": """
<section><h2>Who controls your information</h2><p>LARK Fencing is the controller of personal data collected through this website. Use the email address or phone number shown on our Contact page for privacy questions or requests.</p></section>
<section><h2>Information we collect</h2><p>We collect information you provide in orders, quote requests, contact forms, reviews and account forms, including contact details, delivery address, order information and messages. Essential technical information may also be processed to operate sessions, security and the shopping cart.</p></section>
<section><h2>Why we use it</h2><p>We use personal data to take steps requested before a contract, process and deliver orders, provide quotes and support, comply with tax and accounting obligations, prevent misuse, and pursue legitimate interests in operating and improving the service. Where consent is the lawful basis, it may be withdrawn.</p></section>
<section><h2>Sharing and international services</h2><p>Information may be shared only as needed with hosting, email, delivery, professional-adviser and IT providers, or public authorities where legally required. Embedded maps and externally hosted fonts may connect to third-party services; their own privacy terms may apply.</p></section>
<section><h2>Retention and security</h2><p>We keep data only as long as needed for the purpose collected and applicable legal, tax, warranty and dispute periods. We use reasonable organisational and technical safeguards, but no internet service can promise absolute security.</p></section>
<section><h2>Your rights</h2><p>Depending on the circumstances, you may request access, correction, erasure, restriction, portability, or object to processing. You may complain to Ireland's Data Protection Commission. We may need to verify identity before completing a request.</p></section>""",
        "display_order": 20,
    },
    {
        "title": "Delivery and collection policy",
        "slug": "delivery-and-collection",
        "summary": "How delivery areas, charges, timing, access and collection are confirmed for an order.",
        "body": """
<section><h2>Delivery availability</h2><p>Delivery is subject to product availability, vehicle access and the service area confirmed for your order. A website estimate is not a guaranteed delivery date or charge.</p></section>
<section><h2>Charges and timing</h2><p>We will confirm any delivery charge and expected date or date range before dispatch. We will contact you if a material delay occurs and explain the available options.</p></section>
<section><h2>Access and receipt</h2><p>You must provide a safe, suitable unloading location and disclose narrow roads, restricted access, steps or other obstacles. An adult should be available to receive the delivery and inspect visible condition and quantity. Tell us promptly about missing or visibly damaged goods, without affecting statutory rights.</p></section>
<section><h2>Collection</h2><p>Where collection is agreed, wait for confirmation that the order is ready. Bring the order reference and suitable transport. Risk and responsibility transfer as provided by applicable law and the agreed fulfilment arrangements.</p></section>
<section><h2>Installation</h2><p>Delivery does not include installation unless a written quote or order confirmation expressly includes it. Installation schedules and site requirements are confirmed separately.</p></section>""",
        "display_order": 30,
    },
    {
        "title": "Cancellation and returns policy",
        "slug": "cancellation-and-returns",
        "summary": "How to cancel an online order, return eligible goods, or report faulty, damaged or incorrect products.",
        "body": """
<section><h2>Changing your mind</h2><p>For eligible standard goods bought at a distance, consumers generally have 14 days from receipt to notify us of cancellation, followed by 14 days to return the goods. Contact us by email, phone or the website Contact page with your order number and a clear cancellation request.</p></section>
<section><h2>Goods that may be excluded</h2><p>The change-of-mind right may not apply to goods made to your specifications or clearly personalised, including products cut or made to an agreed non-standard size. We will identify this before the order is binding where it applies. This does not remove rights for faulty, damaged or misdescribed goods.</p></section>
<section><h2>Returning goods</h2><p>Keep eligible goods in reasonable condition and take appropriate care while they are with you. Unless we agree otherwise or the goods are faulty, you are responsible for returning them and for the direct return cost. Fencing products can be bulky; ask us for practical return instructions and a cost estimate before arranging transport.</p></section>
<section><h2>Refunds</h2><p>Eligible refunds are made using an agreed method after cancellation and may be withheld until the goods are returned or evidence of return is supplied, as permitted by law. A deduction may apply for handling beyond what is necessary to establish the nature, characteristics and functioning of the goods.</p></section>
<section><h2>Faulty, damaged or incorrect goods</h2><p>Contact us promptly with the order number, a description and photographs where useful. Consumer remedies for goods that are faulty, not as described or otherwise non-conforming are separate from the change-of-mind process and are not limited by this policy.</p></section>""",
        "display_order": 40,
    },
    {
        "title": "Cookie policy",
        "slug": "cookie-policy",
        "summary": "Information about essential browser storage and third-party resources used by this website.",
        "body": """
<section><h2>What this website stores</h2><p>The website uses essential cookies or browser storage needed for security, sessions, account access, shopping-cart contents and dashboard preferences. Disabling these may stop parts of the service working.</p></section>
<section><h2>Third-party resources</h2><p>Pages may load Google Maps and Google Fonts. Those providers may receive technical information such as an IP address and apply their own cookie and privacy practices. Follow the provider links or browser controls for more information.</p></section>
<section><h2>Analytics and advertising</h2><p>We do not currently describe any non-essential analytics or advertising cookies as active. If these services are introduced, this policy and any required consent controls must be updated before they are enabled.</p></section>
<section><h2>Your controls</h2><p>You can clear or block cookies and site data in your browser settings. Essential features may not function correctly after doing so. Contact us if you have questions about a particular cookie or service.</p></section>""",
        "display_order": 50,
    },
)


def seed_policies(apps, schema_editor):
    LegalPolicy = apps.get_model("core", "LegalPolicy")
    for policy in POLICIES:
        LegalPolicy.objects.update_or_create(
            slug=policy["slug"],
            defaults={
                **policy,
                "version": "Draft 1.0",
                "effective_date": datetime.date(2026, 8, 18),
                "review_status": "review_required",
                "is_active": True,
            },
        )


def remove_seeded_policies(apps, schema_editor):
    LegalPolicy = apps.get_model("core", "LegalPolicy")
    LegalPolicy.objects.filter(slug__in=[policy["slug"] for policy in POLICIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_checkout_eyebrow_for_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.TextField(max_length=500)),
                ('body', models.TextField(help_text='Policy body rendered as trusted HTML on the website.')),
                ('version', models.CharField(default='Draft 1.0', max_length=30)),
                ('effective_date', models.DateField()),
                ('review_status', models.CharField(choices=[('review_required', 'Legal review required'), ('in_review', 'Under legal review'), ('approved', 'Legally approved')], default='review_required', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Legal policies',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.RunPython(seed_policies, remove_seeded_policies),
    ]
