# Generated by Django 5.2.4 on 2026-08-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(blank=True, help_text='Filename from static/assets/images/products/hd, e.g. solid-cottage.png', max_length=255),
        ),
    ]
