# Generated by Django 5.2.4 on 2026-08-18 09:27

from django.db import migrations, models


def preserve_existing_variant_names(apps, schema_editor):
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    for variant in ProductVariant.objects.filter(size=""):
        variant.size = variant.name
        variant.save(update_fields=["size"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productvariant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_name_per_product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='For example: 1.8m (W) × 1.8m (H)', max_length=80),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='style',
            field=models.CharField(blank=True, help_text='For example: Pressure Treated', max_length=80),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='Generated from size and style for carts and orders.', max_length=120),
        ),
        migrations.RunPython(preserve_existing_variant_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'style'), name='unique_variant_options_per_product'),
        ),
    ]
