# Generated by Django 5.2.4 on 2026-08-18 10:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_shiplap_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFenceCalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_width', models.DecimalField(decimal_places=2, default=Decimal('1.80'), help_text='Panel width in metres.', max_digits=6)),
                ('infill_height', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Height added by one infill, in metres.', max_digits=6)),
                ('included_infills', models.PositiveIntegerField(default=5, help_text='Infills included in the base panel-pack price.')),
                ('panel_pack_price', models.DecimalField(decimal_places=2, default=Decimal('160.00'), max_digits=10)),
                ('extra_infill_price', models.DecimalField(decimal_places=2, default=Decimal('29.00'), max_digits=10)),
                ('smartpost_cover_price', models.DecimalField(decimal_places=2, default=Decimal('54.50'), max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'SmartFence calculator settings',
            },
        ),
        migrations.CreateModel(
            name='SmartFenceCalculatorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('trellis', 'Trellis colour'), ('plinth', 'Plinth colour'), ('caps', 'Concrete post-cover colour')], max_length=20)),
                ('name', models.CharField(help_text='Colour or option name shown in the calculator.', max_length=80)),
                ('swatch_class', models.SlugField(help_text='CSS swatch name, e.g. anthracite-swatch.', max_length=80)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('component', 'display_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('component', 'name'), name='unique_smartfence_component_rate')],
            },
        ),
    ]
