# Generated by Django 5.2.4 on 2026-08-18 10:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_seed_smartfence_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCalculatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, help_text='Heading used in the calculator product list. Leave blank to use the product category.', max_length=100)),
                ('panel_width', models.DecimalField(decimal_places=2, default=Decimal('1.80'), help_text='Coverage width of one panel or pack, in metres.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('default_height', models.DecimalField(blank=True, decimal_places=2, help_text='Optional height selected automatically for this product, in metres.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('item_label', models.CharField(default='Panels required', max_length=80)),
                ('post_extra', models.PositiveIntegerField(default=1, help_text='Extra post positions added to the number of panels. Usually 1.')),
                ('pricing_mode', models.CharField(choices=[('quote', 'Request quote'), ('product', 'Use product price'), ('smartfence', 'Use SmartFence calculation')], default='quote', max_length=20)),
                ('unit_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional calculator-only unit price. Leave blank to use the product catalogue price.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calculation_note', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_profile', to='catalog.product')),
            ],
            options={
                'ordering': ('display_order', 'group_name', 'product__name'),
            },
        ),
    ]
