# Generated by Django 5.2.4 on 2026-08-18 11:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_product_calculator_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Fence calculator', max_length=100)),
                ('heading', models.CharField(default='Plan any fence.', max_length=160)),
                ('heading_emphasis', models.CharField(default='Know what you need.', max_length=160)),
                ('introduction', models.TextField(default='Choose an exact fence product and enter the total length and height. We will estimate the number of that product required, its post positions, coverage, and available material pricing.')),
                ('measurement_tip', models.TextField(default='Measure each straight boundary run and add the lengths together. Gates and corners are confirmed during the final review.')),
                ('default_length', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('default_height', models.DecimalField(decimal_places=2, default=Decimal('1.80'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('calculate_button_label', models.CharField(default='Calculate materials', max_length=100)),
                ('default_product', models.ForeignKey(blank=True, help_text='Product selected when the homepage calculator first opens.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_calculator_settings', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'Project calculator settings',
            },
        ),
    ]
