# Generated by Django 5.2.4 on 2026-08-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_seed_homepage_project_calculator_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcalculatorprofile',
            options={'ordering': ('display_order', 'product__category__name', 'product__name')},
        ),
        migrations.RemoveField(
            model_name='productcalculatorprofile',
            name='group_name',
        ),
    ]
