# Generated by Django 5.2.4 on 2026-08-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_use_product_category_for_calculator_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcalculatorsettings',
            name='default_product',
        ),
    ]
