# Generated by Django 5.2.4 on 2026-08-18 13:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(help_text="URL path without domain (e.g., '/about/').", max_length=255, unique=True)),
                ('title', models.CharField(help_text='Page title (up to 100 characters).', max_length=100)),
                ('meta_description', models.TextField(help_text='Meta description (150–160 characters recommended).', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255)),
                ('h1_tag', models.CharField(help_text='Main heading of the page.', max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('image_alt', models.CharField(blank=True, help_text='ALT text for the main or Open Graph image.', max_length=255)),
                ('verification_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_url', models.CharField(blank=True, help_text='Canonical URL for this page (optional).', max_length=255, null=True)),
                ('robots', models.CharField(default='index, follow', help_text="Robots meta tag (e.g., 'index, follow', 'noindex, nofollow').", max_length=100)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (if empty, uses title field).', max_length=100)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description (if empty, uses meta description).', max_length=160)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (1200×630 recommended).', null=True, upload_to='seo/og_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ('url_path',),
            },
        ),
    ]
